import { Hono } from 'hono';
import { cors } from 'hono/cors';
import { swaggerUI } from '@hono/swagger-ui';
import { OpenAPIHono } from '@hono/zod-openapi';
import { logger } from './middlewares/logger';
import { config } from './config/config';
import { db } from './config/db';
import warrantiesRouter from './routes/warranties.routes';

const app = new Hono();
const apiV1 = new OpenAPIHono();

const redact = (value: string | undefined, opts?: { start?: number; end?: number }) => {
  if (!value) return null;
  const start = opts?.start ?? 6;
  const end = opts?.end ?? 4;
  if (value.length <= start + end) return '*'.repeat(value.length);
  return `${value.slice(0, start)}***${value.slice(-end)}`;
};

// CORS middleware
app.use('*', cors({
  origin: config.cors.origins,
  allowHeaders: ['Content-Type', 'Authorization'],
  allowMethods: ['GET', 'POST', 'PATCH', 'PUT', 'DELETE', 'OPTIONS'],
  maxAge: 600,
  credentials: true,
}));

// Logger middleware
app.use('*', logger());

// Health check
app.get('/', (c) => {
  return c.json({ 
    ok: true, 
    service: 'aliado-api-proxy',
    version: '1.0.0',
    environment: config.env,
    timestamp: new Date().toISOString()
  });
});

// Mount warranties routes
apiV1.route('/warranties', warrantiesRouter);

// The OpenAPI documentation will be auto-generated by @hono/zod-openapi
apiV1.doc('/openapi.json', {
  openapi: '3.0.0',
  info: {
    title: 'Aliado API Proxy',
    version: '1.0.0',
    description: 'API REST para interactuar con el proveedor de contabilidad Aliado. Todas las peticiones se autentican automáticamente usando el token Bearer configurado.',
  },
  servers: [
    {
      url: `${config.productionUrl}/api/v1`,
      description: 'Production server',
    },
    {
      url: `http://localhost:${config.port}/api/v1`,
      description: 'Development server',
    },
  ],
});

// Swagger UI
apiV1.get('/doc', swaggerUI({ url: '/api/v1/openapi.json' }));

apiV1.get('/env', (c) => {
  const enabled = config.env !== 'production' || process.env.ENABLE_ENV_DEBUG === 'true';
  if (!enabled) {
    return c.json({ success: false, error: 'Not Found' }, 404);
  }

  const databaseUrl = process.env.DATABASE_URL?.trim();
  const fullRequested = c.req.query('full') === 'true';
  const allowFull =
    config.env !== 'production'
      ? process.env.ALLOW_ENV_FULL === 'true'
      : fullRequested && process.env.ALLOW_ENV_FULL === 'true';

  return c.json({
    success: true,
    environment: config.env,
    env: {
      DATABASE_URL: {
        present: Boolean(databaseUrl),
        preview: redact(databaseUrl, { start: 10, end: 8 }),
        full: allowFull ? databaseUrl ?? null : null,
      },
      DB_HOST: process.env.DB_HOST ?? null,
      DB_PORT: process.env.DB_PORT ?? null,
      DB_NAME: process.env.DB_NAME ?? null,
      DB_USER: process.env.DB_USER ?? null,
      DB_PASSWORD: {
        present: Boolean(process.env.DB_PASSWORD?.trim()),
        preview: redact(process.env.DB_PASSWORD?.trim()),
      },
      PORT: process.env.PORT ?? null,
      NODE_ENV: process.env.NODE_ENV ?? null,
      PRODUCTION_URL: process.env.PRODUCTION_URL ?? null,
      CORS_ORIGIN: process.env.CORS_ORIGIN ?? null,
      ALIADO_API_URL: process.env.ALIADO_API_URL ?? null,
      ALIADO_BEARER_TOKEN: {
        present: Boolean(process.env.ALIADO_BEARER_TOKEN?.trim()),
        preview: redact(process.env.ALIADO_BEARER_TOKEN?.trim()),
      },
      ENABLE_ENV_DEBUG: process.env.ENABLE_ENV_DEBUG ?? null,
      ALLOW_ENV_FULL: process.env.ALLOW_ENV_FULL ?? null,
    },
  });
});

apiV1.get('/db/ping', async (c) => {
  try {
    const result = await db.query('SELECT 1 as ok');
    return c.json({ success: true, ok: true, result: result.rows?.[0] ?? null });
  } catch (err) {
    console.error('DB ping failed:', err);
    const message = err instanceof Error ? err.message : String(err);
    return c.json({ success: false, ok: false, error: 'DB ping failed', message }, 500);
  }
});

// Redirect root /api/v1 to documentation
apiV1.get('/', (c) => {
  return c.redirect('/api/v1/doc');
});

// Mount OpenAPI routes
app.route('/api/v1', apiV1);

// 404 handler
app.notFound((c) => {
  return c.json({ 
    success: false,
    error: 'Not Found', 
    path: c.req.path 
  }, 404);
});

// Error handler
app.onError((err, c) => {
  console.error('Unhandled error:', err);
  return c.json({ 
    success: false,
    error: 'Internal Server Error', 
    message: err.message 
  }, 500);
});

export default app;
